- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: full

- name: Install packages
  ansible.builtin.apt:
    name:
      - software-properties-common
      - apt-transport-https
      - build-essential
      - ca-certificates
      - smartmontools
      - python3-pip
      - lm-sensors
      - iotop
      - htop
      - curl
      - git
    state: present
    update_cache: true
    allow_unauthenticated: true

- name: Update pip
  ansible.builtin.pip:
    name:
      - pip==22.0.4
    state: present

- name: Install pip dependencies
  ansible.builtin.pip:
    name:
      - python-gitlab<=1.12.1
      - virtualenv
      - setuptools

- name: Configure timezone
  community.general.timezone:
    name: "{{ timezone }}"
