services:
  mysql:
    image: mysql:8.0-debian
    container_name: mysql
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      - TZ="Asia/Tehran"
      - MYSQL_ROOT_PASSWORD="example"
      - MYSQL_USER="example"
      - MYSQL_PASSWORD="example"
      - MYSQL_DATABASE="example"
    networks:
      - web
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # mysqld-exporter:
  #   image: bitnami/mysqld-exporter:latest
  #   container_name: mysqld-exporter
  #   restart: unless-stopped
  #   labels:
  #     - "traefik.enable=false"

volumes:
  mysql_data:
    driver: local

networks:
  web:
    external: true
