- name: Ensure directories exists
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: '0644'
  loop:
    - ~/compose
    - ~/compose/mysql

- name: Ensure docker-compose file has been updated
  ansible.builtin.template:
    src: "{{ item }}"
    dest: ~/compose/mysql/
    mode: '0644'
  loop:
    - docker-compose.yml

- name: Ensure mysql compose files are up
  community.docker.docker_compose:
    state: present
    project_src: ~/compose/mysql/
    files:
      - docker-compose.yml
