services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    container_name: postgresql
    restart: unless-stopped
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
    labels:
      - "traefik.enable=false"

  # postgres-exporter:
  #   image: bitnami/postgres-exporter:latest
  #   container_name: postgres-exporter
  #   restart: unless-stopped
  #   labels:
  #     - "traefik.enable=false"

volumes:
  postgresql_data:
    driver: local
